server:
  port: 8083
  servlet:
    context-path: /config-server

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShravaniJawalkar/ecommerce-configs.git
          default-label: master
          search-paths: config-properties
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

logging:
  level:
    org.springframework.cloud.config.server.environment: DEBUG
    org.springframework.web: DEBUG